platforms:
  android:
    versionName: 1.0.0
    versionCode: 1
    packageName: com.twitter.test

    manifest:
      - file: AndroidManifest.xml
        target: manifest/application
        attrs:
          android:usesCleartextTraffic: true

      - file: AndroidManifest.xml
        target: manifest
        inject:
         <uses-permission android:name="android.permission.INTERNET">





